import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "./components/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "control panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ClientProvider>
          <header className="bg-gray-800 text-white p-4">
            <h1> control panel</h1>
          </header>

          <div className="flex flex-1">{children}</div>
        </ClientProvider>
      </body>
    </html>
  );
}
